name: haskell-words
version: 1.0.0.0
github: "MayaChen350/haskell-words"
dependencies:
    - base >= 4.7 && < 5
    - random
    - mtl
    - Cabal-syntax
    - perfect-vector-shuffle
    - vector
    - split
    - directory
executables:
    haskell-words-exe:
        main: Main.hs
        source-dirs: src
