name: haskell-words
version: 0.1.0.0
github: "MayaChen350/haskell-words"
dependencies:
  - base >= 4.7 && < 5
  - random
  - mtl
  - Cabal-syntax
library:
  source-dirs: src/libs
executables:
  haskell-words-exe:
    main: Main.hs
    source-dirs: src
